In [2]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [5]:
from sklearn.datasets import load_iris
iris = load_iris()

In [6]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [7]:
iris.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [8]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    print(model.score(X_test,y_test))

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [17]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

0.9333333333333333


In [18]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9555555555555556


In [19]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9333333333333333


In [21]:
get_score(RandomForestClassifier(n_estimators=60),X_train,X_test,y_train,y_test)

0.9111111111111111


In [30]:
get_score(tree.DecisionTreeClassifier(),X_train,X_test,y_train,y_test)

0.9111111111111111


In [22]:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val_score(LogisticRegression(),iris.data,iris.target,cv=4)

E:\Anaconda\APP\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.97368421, 0.97368421, 0.94594595, 1.        ])

In [25]:
cross_val_score(SVC(),iris.data,iris.target,cv=4)

array([0.97368421, 1.        , 0.94594595, 0.97297297])

In [26]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=4)

array([0.97368421, 0.94736842, 0.94594595, 1.        ])

In [29]:
cross_val_score(tree.DecisionTreeClassifier(),iris.data,iris.target,cv=4)

array([0.97368421, 0.94736842, 0.94594595, 0.97297297])

In [31]:
score1 = cross_val_score(LogisticRegression(),iris.data,iris.target,cv=4)
np.average(score1)

E:\Anaconda\APP\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9733285917496444

In [32]:
score2 = cross_val_score(SVC(),iris.data,iris.target,cv=4)
np.average(score2)

0.9731507823613088

In [33]:
score3 = cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=4)
np.average(score3)

0.9599928876244666

In [35]:
score4 = cross_val_score(tree.DecisionTreeClassifier(),iris.data,iris.target,cv=4)
np.average(score4)

0.9599928876244666